# Site wide configuration

title: Gagan Yatri
locale: en_US
description: Voyages of a Spacefarer
logo: #site/site-logo.jpg
search: true
url: https://gaganyatri.com

# Jekyll configuration
remote_theme: "mmistakes/so-simple-theme"

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins_dir:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: gaganyatri
  email: ""
  twitter: gaganyatri
  github: sachinsshetty


# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/gaganyatri
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/gaganyatri
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/gaganyatri
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
